------------------------------------------------------------------------------
--	FILE:	  player_multiplayer.lua
--	AUTHOR:   Julian Meyer
--	PURPOSE:  Class to represent an online player
------------------------------------------------------------------------------
